# Generated by Django 3.1.4 on 2020-12-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(db_index=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Published'),
        ),
    ]
