# Generated by Django 3.1.4 on 2020-12-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20201208_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(db_index=True, verbose_name='Created'),
        ),
    ]
