# Generated by Django 3.1.4 on 2020-12-10 00:46

from django.db import migrations
import sledilnik.easymde.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20201208_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blurb',
            field=sledilnik.easymde.models.MarkdownField(verbose_name='Blurb'),
        ),
        migrations.AlterField(
            model_name='post',
            name='blurb_en',
            field=sledilnik.easymde.models.MarkdownField(null=True, verbose_name='Blurb'),
        ),
        migrations.AlterField(
            model_name='post',
            name='blurb_sl',
            field=sledilnik.easymde.models.MarkdownField(null=True, verbose_name='Blurb'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=sledilnik.easymde.models.MarkdownField(blank=True, null=True, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body_en',
            field=sledilnik.easymde.models.MarkdownField(blank=True, null=True, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body_sl',
            field=sledilnik.easymde.models.MarkdownField(blank=True, null=True, verbose_name='Body'),
        ),
    ]
