# Generated by Django 3.1.4 on 2020-12-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20201210_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='on_homepage',
            field=models.BooleanField(db_index=True, default=False, verbose_name='On home page'),
        ),
    ]
