# Generated by Django 3.1.4 on 2020-12-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_on_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['pinned', '-created', 'title'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='on_homepage',
        ),
        migrations.AddField(
            model_name='post',
            name='pinned',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Pinned'),
        ),
    ]
