# Generated by Django 3.1.4 on 2020-12-15 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20201215_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pinned', '-created', 'title'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
