# Generated by Django 3.1.4 on 2020-12-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20201215_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_caption',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Image caption'),
        ),
    ]
