# Generated by Django 3.1.4 on 2020-12-11 11:13

from django.db import migrations, models
import django.db.models.deletion
import sledilnik.easymde.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('password', models.CharField(help_text='Used to authenticate against the API. Hashed form.', max_length=100, verbose_name='Password')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('contact_name', models.CharField(max_length=100, verbose_name='Contact name')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Contact email')),
                ('www', models.URLField(blank=True, null=True, verbose_name='Home page')),
                ('description', sledilnik.easymde.models.MarkdownField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Models',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PredictionIntervalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('description', sledilnik.easymde.models.MarkdownField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Prediction interval type',
                'verbose_name_plural': 'Prediction interval types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PredictionIntervalWidth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveIntegerField(unique=True, verbose_name='Width')),
            ],
            options={
                'verbose_name': 'Prediction interval width',
                'verbose_name_plural': 'Prediction interval widths',
                'ordering': ['width'],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('description', sledilnik.easymde.models.MarkdownField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Modelling scenario',
                'verbose_name_plural': 'Modelling scenarios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('date', models.DateField(verbose_name='Date')),
                ('interval_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='models.predictionintervaltype', verbose_name='Interval type')),
                ('interval_width', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='models.predictionintervalwidth', verbose_name='Interval width')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models.model', verbose_name='Model')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models.scenario', verbose_name='Scenario')),
            ],
            options={
                'verbose_name': 'Prediction',
                'verbose_name_plural': 'Predictions',
                'ordering': ['-date', 'model__name'],
                'unique_together': {('date', 'model')},
            },
        ),
        migrations.CreateModel(
            name='PredictionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.PositiveIntegerField(verbose_name='Date')),
                ('icu', models.PositiveIntegerField(verbose_name='ICU')),
                ('icuLowerBound', models.PositiveIntegerField(blank=True, null=True, verbose_name='ICU lower bound')),
                ('icuUpperBound', models.PositiveIntegerField(blank=True, null=True, verbose_name='ICU upper bound')),
                ('hospitalized', models.PositiveIntegerField(verbose_name='Hospitalized')),
                ('hospitalizedLowerBound', models.PositiveIntegerField(blank=True, null=True, verbose_name='Hospitalized lower bound')),
                ('hospitalizedUpperBound', models.PositiveIntegerField(blank=True, null=True, verbose_name='Hospitalized upper bound')),
                ('deceased', models.PositiveIntegerField(verbose_name='Deceased')),
                ('deceasedLowerBound', models.PositiveIntegerField(blank=True, null=True, verbose_name='Deceased lower bound')),
                ('deceasedUpperBound', models.PositiveIntegerField(blank=True, null=True, verbose_name='Deceased upper bound')),
                ('deceasedToDate', models.PositiveIntegerField(verbose_name='DeceasedToDate')),
                ('deceasedToDateLowerBound', models.PositiveIntegerField(blank=True, null=True, verbose_name='Deceased todate lower bound')),
                ('deceasedToDateUpperBound', models.PositiveIntegerField(blank=True, null=True, verbose_name='Deceased todate upper bound')),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models.prediction', verbose_name='Prediction')),
            ],
            options={
                'verbose_name': 'Prediction data',
                'verbose_name_plural': 'Prediction data',
                'ordering': ['-date', 'prediction'],
                'unique_together': {('prediction', 'date')},
            },
        ),
    ]
