# Generated by Django 3.1.4 on 2020-12-16 17:17

from django.db import migrations, models
import sledilnik.easymde.models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='description_en',
            field=sledilnik.easymde.models.MarkdownField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='model',
            name='description_sl',
            field=sledilnik.easymde.models.MarkdownField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='model',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='model',
            name='name_sl',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='model',
            name='www_en',
            field=models.URLField(blank=True, null=True, verbose_name='Home page'),
        ),
        migrations.AddField(
            model_name='model',
            name='www_sl',
            field=models.URLField(blank=True, null=True, verbose_name='Home page'),
        ),
        migrations.AddField(
            model_name='predictionintervaltype',
            name='description_en',
            field=sledilnik.easymde.models.MarkdownField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='predictionintervaltype',
            name='description_sl',
            field=sledilnik.easymde.models.MarkdownField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='predictionintervaltype',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='predictionintervaltype',
            name='name_sl',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='description_en',
            field=sledilnik.easymde.models.MarkdownField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='description_sl',
            field=sledilnik.easymde.models.MarkdownField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='name_sl',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Name'),
        ),
    ]
