# Generated by Django 3.1.4 on 2020-12-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20201216_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='model',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='model',
            name='contact_name',
        ),
        migrations.AddField(
            model_name='model',
            name='contacts',
            field=models.ManyToManyField(to='models.Person', verbose_name='Contacts'),
        ),
    ]
