# Generated by Django 3.1.4 on 2020-12-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_auto_20201216_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionintervaltype',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scenario',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
