# Generated by Django 3.1.4 on 2020-12-17 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_auto_20201216_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prediction',
            name='interval_width',
        ),
        migrations.DeleteModel(
            name='PredictionIntervalWidth',
        ),
    ]
