# Generated by Django 3.1.4 on 2020-12-17 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_auto_20201217_2130'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prediction',
            unique_together={('date', 'model', 'scenario', 'interval_kind')},
        ),
    ]
