# Generated by Django 3.1.4 on 2020-12-21 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_auto_20201217_2132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predictiondata',
            options={'ordering': ['prediction'], 'verbose_name': 'Prediction data', 'verbose_name_plural': 'Prediction data'},
        ),
        migrations.AlterUniqueTogether(
            name='predictiondata',
            unique_together={('prediction',)},
        ),
        migrations.RemoveField(
            model_name='predictiondata',
            name='date',
        ),
    ]
