# Generated by Django 3.1.4 on 2020-12-21 10:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_auto_20201221_1104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predictiondata',
            options={'ordering': ['-date', 'prediction'], 'verbose_name': 'Prediction data', 'verbose_name_plural': 'Prediction data'},
        ),
        migrations.AddField(
            model_name='predictiondata',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='predictiondata',
            unique_together={('prediction', 'date')},
        ),
    ]
