version: '3.4'
services:
  app:
    user: vscode

    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: 3.8
        INSTALL_NODE: "false"

    environment:
      DJANGO_SETTINGS_MODULE: sledilnik.settings.devcontainer
    
    volumes:
      - ..:/website-backend:cached

    command: /bin/sh -c "while sleep 1000; do :; done"

  postgres:
    image: postgres:11.10
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sledilnik
    volumes:
       - pg-data:/var/lib/postgresql/data

 
volumes:
  pg-data: