# Generated by Django 3.1.7 on 2021-11-24 13:01

from django.db import migrations, models
import django.db.models.deletion
import sledilnik.easymde.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Project name')),
                ('name_sl', models.CharField(max_length=100, null=True, unique=True, verbose_name='Project name')),
                ('name_en', models.CharField(max_length=100, null=True, unique=True, verbose_name='Project name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Position')),
                ('question', models.CharField(max_length=500, verbose_name='Question')),
                ('question_sl', models.CharField(max_length=500, null=True, verbose_name='Question')),
                ('question_en', models.CharField(max_length=500, null=True, verbose_name='Question')),
                ('answer', sledilnik.easymde.models.MarkdownField(verbose_name='Answer')),
                ('answer_sl', sledilnik.easymde.models.MarkdownField(null=True, verbose_name='Answer')),
                ('answer_en', sledilnik.easymde.models.MarkdownField(null=True, verbose_name='Answer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faq.project', verbose_name='Project')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
