# Generated by Django 3.1.7 on 2021-11-24 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_auto_20211124_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name_sl',
        ),
    ]
