# Generated by Django 3.1.7 on 2021-11-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0007_auto_20211125_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossaryterm',
            name='slug',
            field=models.SlugField(help_text='Used to reference the glossary term in the FAQ text: &lt;span data-term=&quot;slug&quot;&gt;some term&lt;/span&gt;', max_length=100, verbose_name='Slug'),
        ),
    ]
