# Generated by Django 3.1.7 on 2021-11-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0009_faq_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='slug_en',
            field=models.SlugField(blank=True, help_text='Used to reference the question with a hash link, e.g. https://sledilnik.org/faq#slug', max_length=100, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='faq',
            name='slug_sl',
            field=models.SlugField(blank=True, help_text='Used to reference the question with a hash link, e.g. https://sledilnik.org/faq#slug', max_length=100, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='glossaryterm',
            name='slug_en',
            field=models.SlugField(help_text='Used to reference the glossary term in the FAQ text: &lt;span data-term=&quot;slug&quot;&gt;some term&lt;/span&gt;', max_length=100, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='glossaryterm',
            name='slug_sl',
            field=models.SlugField(help_text='Used to reference the glossary term in the FAQ text: &lt;span data-term=&quot;slug&quot;&gt;some term&lt;/span&gt;', max_length=100, null=True, verbose_name='Slug'),
        ),
    ]
