# Generated by Django 3.1.7 on 2021-11-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0010_auto_20211126_1918'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='glossaryterm',
            name='unique_slug_per_project',
        ),
        migrations.AddConstraint(
            model_name='glossaryterm',
            constraint=models.UniqueConstraint(fields=('project', 'slug_sl'), name='unique_slug_sl_per_project'),
        ),
        migrations.AddConstraint(
            model_name='glossaryterm',
            constraint=models.UniqueConstraint(fields=('project', 'slug_en'), name='unique_slug_en_per_project'),
        ),
    ]
