name: Build and deploy (production)

on:
  release: 
    types: [published]

env:
  RELEASE_NAME: website-backend
  CHART_VALUES_FILE: .helm/values.prod.yml
  DEPLOY_NAMESPACE: sledilnik-prod
  IMAGE_TAG: ${{ github.event.release.tag_name }}
  DEPLOY_ENV: production
  DEPLOY_URL: https://backend.sledilnik.org

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ghcr.io
        uses: docker/login-action@v1.14.0 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      
      - name: Build and push docker container image
        uses: docker/build-push-action@v2.4.0
        with:
          push: true
          context: .
          file: ./Dockerfile
          tags: |
            ghcr.io/${{ github.repository_owner }}/website-backend:${{ env.IMAGE_TAG}}

  deploy:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Deploy
        uses: sledilnik/action-helm-deploy@v1.0.2
        with:
          chartName: sledilnik/django
          chartVersion: '1.0.1'
          kubeconfig: '${{ secrets.KUBECONFIG }}'        